[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["franc90 <azarnowski1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
